### ISSUE TITLE
Can we integrate the results directly into the Alfred search window (skipping the keyword)?

### ISSUE THREAD

**Issue by githorse** [blainesch/alfred-chrome-bookmarks#18]
It would be great to have these bookmark results included in the default search results along with files, folders, URL history, and whatever else is in there. Ideally, this would work in addition to using the workflow with a keyword (.e.g, `,b`), not replace it, so I could do it either way. Is this possible?

**Comment by blainesch** [comment]
Unfortunately, alfred does not allow this. The only fallback search a plugin can generate is a non-scripted one... similar to `google` or `amazon` links you see.

One option you can do is set a hotkey in the workflow to point to the script filter.

<img width="484" alt="alfred_preferences" src="https://cloud.githubusercontent.com/assets/769039/14064108/09d10950-f3aa-11e5-9667-5fb84929814a.png">

<img width="594" alt="03_26_16 at 11 27 46pm" src="https://cloud.githubusercontent.com/assets/769039/14064120/5fe496cc-f3aa-11e5-851f-89cf15b8abba.png">

**Comment by githorse** [comment]
Thank you, Blaine -- the keyword and/or hotkey will suffice for now.

On Sun, Mar 27, 2016 at 2:28 AM, Blaine Schmeisser <notifications@github.com
> wrote:

> Unfortunately, alfred does not allow this. The only fallback search a
> plugin can generate is a non-scripted one... similar to google or amazon
> links you see.
>
> One option you can do is set a hotkey in the workflow to point to the
> script filter.
>
> [image: alfred_preferences]
> <https://cloud.githubusercontent.com/assets/769039/14064108/09d10950-f3aa-11e5-9667-5fb84929814a.png>
>
> [image: 03_26_16 at 11 27 46pm]
> <https://cloud.githubusercontent.com/assets/769039/14064120/5fe496cc-f3aa-11e5-851f-89cf15b8abba.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/blainesch/alfred-chrome-bookmarks/issues/18#issuecomment-202000669>
>



-- 
<https://www.google.com/search?hl=en&q=je+ne+sais+quoi&um=1&ie=UTF-8&tbm=isch&source=og>
Ryan Corbett Turner
rct189@gmail.com | 505.847.6189
