### ISSUE TITLE
Histories are noisy

### ISSUE THREAD

**Issue by kyoh86** [blainesch/alfred-chrome-bookmarks#24]
When I search a bookmark, but many pages are found from history.

![alfred-chrome-bookmarks 2017-06-01 09-32-02](https://cloud.githubusercontent.com/assets/5582459/26659694/83c36bca-46ad-11e7-87d8-072117df941e.png)
In above case, the top of them is my bookmark so it's still better.

They're noisy...

**Comment by bayleedev** [comment]
If you look at your `Bookmarks` file are these in there as well?

My guess is that these are bookmarked under your current profile or another profile. Searching the history is not something this plugin does.

For specifying a more specific profile you can look here:

https://github.com/blainesch/alfred-chrome-bookmarks#multiple-or-single-profiles
