### ISSUE TITLE
Add support for searching for symbol characters like [ , ] , + , – , ^ , etc.

### ISSUE THREAD

**Issue by Jyqft** [blainesch/alfred-chrome-bookmarks#9]
This would be useful for searching bookmark items whose name or URL have symbols on them.

The workflow here (https://github.com/manifestinteractive/alfred-workflows/tree/master/Chrome%20History) seems to have some support for this.

**Comment by blainesch** [comment]
The reason this is broken is because we make a regex from the characters entered. I'll guess it's not being escaped correctly.

https://github.com/blainesch/alfred-chrome-bookmarks/blob/master/src/alfmarks.php#L97

**Comment by blainesch** [comment]
Using something like [`preg_quote`](http://php.net/manual/en/function.preg-quote.php) could potentially fix this issue. I'll play with something later.

**Comment by Jyqft** [comment]
Nice, that does enable some special characters to be searchable. Although, replacing the old bookmarks.php with the new alfmarks.php only worked when I added this to the bottom of alfmarks.php:
`echo BookmarkModel::find($_SERVER['argv'][1])->sort()->to_xml();`

Also, some of my bookmarks have the following characters, which the implementation in v1.1 does not yet support:
* `#` (number sign)
* `&` (ampersand)
* `*` (asterisk) — seems to take a lot longer to search (and then fail) than other unsupported characters
* `_` (underscore)
* `|` (vertical bar)
* `'` (apostrophe)
* `<` (less than sign)
* `>` (greater than sign
* `/` (forward slash)
* `~` (tilde)

I got this by limiting the bookmarks search to 1 bookmark item containing all common symbols that are printed on the Apple keyboards (excluding the command symbol), and then typing the following characters, one at a time:
`` ! @ # $ % ^ & * ( ) - – — _ = + [ { ] } \ | ; : ' " , < . > / ? ` ~ ``

**Comment by blainesch** [comment]
Items such as the number sign and greater then sign cannot be used at the beginning of the first argument as a restriction from alfred. They work if they are not the first character, as far as I have tested using this new code.

**Comment by Jyqft** [comment]
Number sign does seem to work when not at the beginning of the first argument, but greater sign doesn't. 

What about the other characters?
